import{a as p,S as h,i as d}from"./assets/vendor-lDhL-8I6.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=a(r);fetch(r.href,t)}})();const L="22970342-054b8243005dd74f99097cd8f",P="https://pixabay.com/api/",w=15;async function g(e,l=1){try{const a=await p.get(P,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:w,page:l}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.error("Error fetching images:",a),new Error("Failed to fetch images. Please try again later.")}}function M(e,l){const a=l.map(({webformatURL:r,largeImageURL:t,tags:c,likes:f,views:u,comments:y,downloads:m})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${t}">
            <img
              class="gallery-image"
              src="${r}"
              alt="${c}"
            />
            <ul class="gallery-info">
              <li class="gallery-info-item">Likes <span class="descr-span">${f}</span></li>
              <li class="gallery-info-item">Views <span class="descr-span">${u}</span></li>
              <li class="gallery-info-item">Comments <span class="descr-span">${y}</span></li>
              <li class="gallery-info-item">Downloads <span class="descr-span">${m}</span></li>
            </ul> 
          </a>
        </li>   
      `).join("");console.log(a),e.insertAdjacentHTML("beforeend",a),new h(".gallery-item a",{captionDelay:250,scrollZoom:!1}).refresh()}function q(e){e.innerHTML=""}function b(e){e.classList.remove("hidden")}function E(e){e.classList.add("hidden")}function S(e){e.style.display="block"}function v(e){e.style.display="none"}const i={renderGalleryCard:M,clearGallery:q,showLoader:b,hiddeLoader:E,showLoadMore:S,hideLoadMore:v},s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},o={query:"",page:0,totalPage:0};s.form.addEventListener("submit",R);s.loadMoreBtn.addEventListener("click",x);async function R(e){e.preventDefault();const l=e.currentTarget;if(o.query=l.elements.search_text.value.trim(),!o.query){d.warning({title:"Warning",message:"Please enter a value",position:"topRight"});return}o.page=1,i.clearGallery(s.gallery),i.showLoader(s.loader),i.hideLoadMore(s.loadMoreBtn);try{const{images:a,totalHits:n}=await g(o.query,o.page);o.totalPage=Math.ceil(n/15),a.length===0?d.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(i.renderGalleryCard(s.gallery,a),o.page<o.totalPage&&i.showLoadMore(s.loadMoreBtn))}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.hiddeLoader(s.loader)}}async function x(){o.page+=1,i.showLoader(s.loader),i.showLoadMore(s.loadMoreBtn);try{const{images:e}=await g(o.query,o.page);i.renderGalleryCard(s.gallery,e),o.page>=o.totalPage&&d.warning({title:"Warning",message:"No more images to load.",position:"topRight"})}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{i.hiddeLoader(s.loader)}}
//# sourceMappingURL=index.js.map
