import{a as w,i as b,S as q}from"./assets/vendor-BfjKTZs6.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const l of r)if(l.type==="childList")for(const c of l.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const l={};return r.integrity&&(l.integrity=r.integrity),r.referrerPolicy&&(l.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?l.credentials="include":r.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function n(r){if(r.ep)return;r.ep=!0;const l=o(r);fetch(r.href,l)}})();const M="22970342-054b8243005dd74f99097cd8f",S="https://pixabay.com/api/",B=15;async function g(e,a=1){try{const o=await w.get(S,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:a}});return{images:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.error("Error fetching images:",o),new Error("Failed to fetch images. Please try again later.")}}function f(e,a){const o=a.map(({webformatURL:r,largeImageURL:l,tags:c,likes:p,views:h,comments:P,downloads:L})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img
              class="gallery-image"
              src="${r}"
              alt="${c}"
            />
            <ul class="gallery-info">
              <li class="gallery-info-item">Likes <span class="descr-span">${p}</span></li>
              <li class="gallery-info-item">Views <span class="descr-span">${h}</span></li>
              <li class="gallery-info-item">Comments <span class="descr-span">${P}</span></li>
              <li class="gallery-info-item">Downloads <span class="descr-span">${L}</span></li>
            </ul> 
          </a>
        </li>   
      `).join("");e.insertAdjacentHTML("beforeend",o),new q(".gallery-item a",{captionDelay:250,scrollZoom:!1}).refresh()}function v(e){e.innerHTML=""}function u(e){e.classList.remove("hidden")}function d(e){e.classList.add("hidden")}function y(e){e.style.display="block"}function m(e){e.style.display="none"}function i(e,a){b[a]({title:a.toUpperCase(),message:e,position:"bottomRight"})}const t={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},s={query:"",page:0,totalPage:0};function E(){window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"})}t.form.addEventListener("submit",x);t.loadMoreBtn.addEventListener("click",$);async function x(e){e.preventDefault();const a=e.currentTarget;if(s.query=a.elements.search_text.value.trim(),!s.query){i("Please enter a value","warning");return}s.page=1,v(t.gallery),u(t.loader),m(t.loadMoreBtn);try{setTimeout(async()=>{try{const{images:o,totalHits:n}=await g(s.query,s.page);s.totalPage=Math.ceil(n/15),o.length===0?i("Sorry, there are no images matching your search query. Please try again!","info"):(f(t.gallery,o),s.page<s.totalPage&&y(t.loadMoreBtn))}catch{i("Failed to fetch images. Please try again later.","error")}finally{d(t.loader)}},1e3)}catch{i("Failed to fetch images. Please try again later.","error")}a.reset()}async function $(){s.page+=1,u(t.loader),y(t.loadMoreBtn);try{setTimeout(async()=>{try{const{images:e}=await g(s.query,s.page);f(t.gallery,e),E(),s.page>=s.totalPage&&(i("No more images to load.","warning"),m(t.loadMoreBtn))}catch{i("Failed to fetch images. Please try again later.","error")}finally{d(t.loader)}},500)}catch{i("Failed to fetch images. Please try again later.","error")}finally{d(t.loader)}}
//# sourceMappingURL=index.js.map
